### ISSUE TITLE
Environment variable for HTTPURL seemingly ignored

### ISSUE THREAD

**Issue by bhartshorn** [Zepmann/lldap-cli#4] opened 2024-02-26 00:58 UTC
Hello,

It seems like setting `$LLDAP_HTTPURL` is not taking effect, unless I'm missing something. Note that this is in `fish` shell, but `$LLDAP_TOKEN` is working fine, so I don't think the shell is to blame here. I had a glance through the source but didn't see an obvious cause.

```
> echo $LLDAP_HTTPURL
http://somehost:17170
> lldap user list
ERROR: Connection error to lldap web interface: http://localhost:17170/api/graphql
```

**Comment by Zepmann** [comment] 2024-02-26 16:05
Note that it is not enough to set the environment variables as part of your current environment. You will have to either add them to the command line of LLDAP-CLI, or export them.

Try:
```
export LLDAP_HTTPURL="http://somehost:17170"
```

Before running LLDAP-CLI.

I do not provide support for other shells, but it should work in any shell that is reasonably Bash compatible. Let me know if it works. If not, please retest in Bash.

**Comment by Zepmann** [comment] 2024-08-07 07:43
I'll retest variable LLDAP_HTTPURL in the coming week.

**Comment by Zepmann** [comment] 2024-08-25 19:50
Cannot reproduce:
```
# LLDAP_HTTPURL="http://doesnotexist.example:17100" ./lldap-cli user list
ERROR: Connection error to lldap web interface: http://doesnotexist.example:17100/auth/simple/login
ERROR:

# export LLDAP_HTTPURL="http://doesnotexist.example:17100"
# ./lldap-cli user list
ERROR: Connection error to lldap web interface: http://doesnotexist.example:17100/auth/simple/login
ERROR:
```

Second empty ERROR line is a bug and will be fixed.

**Closed** 2024-08-25 20:40 UTC
